/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Final_Project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        // assertNotNull(classUnderTest.main(), "app should have a greeting");
    }
}
